compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: auto
  offload_optimizer_device: auto
  offload_param_device: auto
  zero3_init_flag: false
  zero_stage: 2  # 7B模型推荐使用stage2
distributed_type: NO
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16  # A100/V100推荐fp16，A10推荐bf16
num_machines: 1
num_processes: 1  # 需与GPU数量一致
rdzv_backend: static
same_network: true
use_cpu: false